# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pR8qSWcsQt82d76aABzA_pjJDyBGZhyj
"""

# To determine which version you're using:
!pip show tensorflow

# For the current version: 
!pip install --upgrade tensorflow

# For a specific version:
!pip install tensorflow==1.2

# For the latest nightly build:
!pip install tf-nightly

!pip install imageAI

!pip install tensorflow==1.15.2

!unzip /content/idenprof-jpg.zip

from imageai.Prediction.Custom import ModelTraining

model_trainer = ModelTraining()
model_trainer.setModelTypeAsResNet()
model_trainer.setDataDirectory("/content/drive/My Drive/idenprof-jpg/idenprof")
model_trainer.trainModel(num_objects=10, num_experiments=200, enhance_data=True, batch_size=32, show_network_summary=True)

from imageai.Prediction.Custom import CustomImagePrediction
import os

execution_path = os.getcwd()

professionPrediction = CustomImagePrediction()
professionPrediction.setModelTypeAsResNet()

#This is the modal after training with 2000 + pictures
professionPrediction.setModelPath("idenprof_061-0.7933.h5")
#This is the .json file with user-customized image classes 
professionPrediction.setJsonPath("idenprof_model_class.json")
professionPrediction.loadModel(num_objects=10)

predictions, probabilities = professionPrediction.predictImage("/content/testImages/JiuruChen.JPG", result_count=5)
#predictions, probabilities = professionPrediction.predictImage("/content/testImages/1.jpg", result_count=5)

for indiPred, indiProba in zip(predictions, probabilities):
    print(indiPred , " : " , indiProba)